// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFlowCateModel = "flow_cate"

// FlowCateModel mapped from table <flow_cate>
type FlowCateModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name       string         `gorm:"column:name"` // 分类名
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName FlowCateModel's table name
func (*FlowCateModel) TableName() string {
	return TableNameFlowCateModel
}
