// Code generated by goctl. DO NOT EDIT.
package form

import (
	"go-flow-admin/handler/flow/form"
	"go-flow-admin/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterFlowFormRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/flow/form", form.ListHandle)
	g.GET("/flow/form/:key/:version", form.DetailHandle)
	g.POST("/flow/form", form.AddHandle)
	g.PUT("/flow/form/:key/:version", form.EditHandle)
	g.DELETE("/flow/form/:id", form.DelHandle)

}
