// Code generated by goctl. DO NOT EDIT.
package base

type FlowcateResponse struct {
	List []FlowCateData `json:"list"` // 分类
}

type FlowCateData struct {
	Id   int    `json:"id"`   // ID
	Name string `json:"name"` // 分类名
}

type FlowFormResponse struct {
	List []BaseFlowFormList `json:"list"`
}

type BaseFlowFormList struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Version     int    `json:"version"`
	Description string `json:"description"`
}

type FlowFormViewRequest struct {
	Key     string `uri:"key"`
	Version int    `uri:"version"`
}

type FlowFormViewResponse struct {
	Rule   string `json:"rule"`
	Option string `json:"option"`
}
