// Code generated by goctl. DO NOT EDIT.
package task

import (
	"go-flow-admin/handler/flow/task"
	"go-flow-admin/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterFlowTaskRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/flow/task_assignee", task.AssigneeHandle)
	g.GET("/flow/task_candidate", task.CandidateHandle)
	g.GET("/flow/task/:id", task.DetailHandle)
	g.PUT("/flow/task_complete/:id", task.CompleteHandle)
	g.PUT("/flow/task_complete_with_form/:id", task.CompleteWithFormHandle)
	g.PUT("/flow/task_delegate/:id", task.DelegateHandle)
	g.POST("/flow/attachment/:id", task.AddAttachmentHandle)
	g.DELETE("/flow/attachment/:taskId/:fileId", task.DelAttachmentHandle)
	g.GET("/flow/attachment/:taskId/:attachmentId/:fileName", task.DownloadAttachmentHandle)
	g.POST("/flow/comment/:taskId", task.AddCommentHandle)
	g.DELETE("/flow/comment/:taskId/:commentId", task.DelCommentHandle)

}
