// Code generated by goctl. DO NOT EDIT.
package instance

type ProcessInstanceRequest struct {
	Page        int    `form:"page" label:"分页"`            // 分页
	PageSize    int    `form:"pageSize" label:"每页条数"`      // 每页条数
	ProcessName string `form:"processName" label:"流程名称"`   // 流程名称
	StartTime   string `form:"startTime" label:"流程开始时间区间"` // 流程开始时间区间
	EndTime     string `form:"endTime" label:"流程开始时间区间"`   // 流程开始时间区间
}

type ProcessInstanceResponse struct {
	Page     int                   `json:"page"`     // 分页
	PageSize int                   `json:"pageSize"` // 每页条数
	Total    int                   `json:"total"`    // 总条数
	Data     []ProcessInstanceList `json:"data"`     // 具体数据
}

type ProcessInstanceList struct {
	Id          string `json:"id"`          // ID
	ProcessName string `json:"processName"` // 流程名称
	StartTime   string `json:"startTime"`   // 流程开始时间
	EndTime     string `json:"endTime"`     // 流程结束时间
	Duration    int    `json:"duration"`    // 流程使用时间
	CurrentTask string `json:"currentTask"` // 当前节点
	CurrentUser string `json:"currentUser"` // 当前节点执行人
}

type ProcessInstanceDetailResponse struct {
	History []Action `json:"history"` // 历史流转
}

type ProcessInstanceDetailRequest struct {
	Id string `uri:"id"`
}

type Action struct {
	TaskId         string       `json:"taskId"`         // 任务ID
	ActionName     string       `json:"actionName"`     // 执行步骤
	HandelUser     string       `json:"handelUser"`     // 操作人
	CreateTime     string       `json:"createTime"`     // 开始时间
	HandleTime     string       `json:"handleTime"`     // 操作时间
	UseTime        int          `json:"useTime"`        // 共计操作时间
	Comment        []Comment    `json:"comment"`        // 备注
	Attachment     []Attachment `json:"attachment"`     // 附件
	FormRule       string       `json:"formRule"`       // 表单使用
	FormOption     string       `json:"formOption"`     // 表单使用
	FormProperties []Properties `json:"formProperties"` // 表单填写的值
}

type Comment struct {
	Id      string `json:"id"`      // 备注ID
	TaskId  string `json:"taskId"`  // 任务ID
	Message string `json:"message"` // 备注内容
	Author  string `json:"author"`  // 上传人
	Time    string `json:"time"`    // 备注时间
}

type Attachment struct {
	Id          string `json:"id"`          // 附件ID
	TaskId      string `json:"taskId"`      // 任务ID
	Url         string `json:"url"`         // 附件URL
	Author      string `json:"author"`      // 上传人
	Name        string `json:"name"`        // 附件名
	Description string `json:"description"` // 附件描述
	Time        string `json:"time"`        // 上传时间
}

type Properties struct {
	Id    string      `json:"id"`
	Value interface{} `json:"value"`
}
