// Code generated by goctl. DO NOT EDIT.
package base

import (
	"go-flow-admin/handler/flow/base"
	"go-flow-admin/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterFlowBaseRoute(e *gin.Engine) {
	g := e.Group("/base")
	g.Use(middleware.JwtMiddleware)
	g.GET("/flowcate", base.FlowcateHandle)
	g.GET("/flowform", base.FlowformHandle)
	g.GET("/flowformveiw/:key", base.FlowformveiwHandle)

}
