// Code generated by goctl. DO NOT EDIT.
package cate

type FlowCateListRequest struct {
	Page     int `form:"page" label:"分页"`       // 分页
	PageSize int `form:"pageSize" label:"每页条数"` // 每页条数
}

type FlowCateListResponse struct {
	Page     int            `json:"page"`     // 分页
	PageSize int            `json:"pageSize"` // 每页条数
	Total    int            `json:"total"`    // 总条数
	Data     []FlowCateList `json:"data"`     // 具体数据
}

type FlowCateList struct {
	Id         int    `json:"id"`         // ID
	Name       string `json:"name"`       // 分类名
	CreateTime string `json:"createTime"` // 创建时间
}

type AddFlowCateRequest struct {
	Name string `json:"name" binding:"required" label:"分类名"` // 分类名
}

type EditFlowCateRequest struct {
	Id   int    `uri:"id" label:"ID"`                        // ID
	Name string `json:"name" binding:"required" label:"分类名"` // 分类名
}

type DeleteFlowCateRequest struct {
	Id int `uri:"id" label:"ID"` // ID
}
