// Code generated by goctl. DO NOT EDIT.
package task

type TaskListRequest struct {
	Page     int `form:"page" label:"分页"`       // 分页
	PageSize int `form:"pageSize" label:"每页条数"` // 每页条数
}

type TaskListResponse struct {
	Page     int        `json:"page"`     // 分页
	PageSize int        `json:"pageSize"` // 每页条数
	Total    int        `json:"total"`    // 总条数
	Data     []TaskList `json:"data"`     // 具体数据
}

type TaskList struct {
	Id                string `json:"id"`                // 任务ID
	ProcessName       string `json:"processName"`       // 任务名称
	TaskName          string `json:"taskName"`          // 任务名称
	ProcessInstanceId string `json:"processInstanceId"` // 流程实例ID
	CreateTime        string `json:"createTime"`        // 任务创建时间
}

type TaskDetailResponse struct {
	Form    []Form   `json:"form"`    // 填写的表单
	History []Action `json:"history"` // 历史流转
	Event   []Event  `json:"event"`   // 操作日志
}

type Form struct {
	Id    string      `json:"id"`    // 表单ID
	Name  string      `json:"name"`  // 表单名
	Type  string      `json:"type"`  // 表单格式
	Value interface{} `json:"value"` // 表单值
}

type Action struct {
	ActionName string       `json:"actionName"` // 执行步骤
	HandelUser string       `json:"handelUser"` // 操作人
	CreateTime string       `json:"createTime"` // 开始时间
	HandleTime string       `json:"handleTime"` // 操作时间
	UseTime    int          `json:"useTime"`    // 共计操作时间
	Comment    []Comment    `json:"comment"`    // 备注
	Attachment []Attachment `json:"attachment"` // 附件
}

type Event struct {
	Id     string `json:"id"`     // ID
	Author string `json:"author"` // 操作人
	Name   string `json:"name"`   // 操作类型
	Time   string `json:"time"`   // 操作时间
}

type Comment struct {
	Id      string `json:"id"`      // 备注ID
	TaskId  string `json:"taskId"`  // 任务ID
	Message string `json:"message"` // 备注内容
	Author  string `json:"author"`  // 上传人
	Time    string `json:"time"`    // 备注时间
}

type Attachment struct {
	Id          string `json:"id"`          // 附件ID
	TaskId      string `json:"taskId"`      // 任务ID
	Url         string `json:"url"`         // 附件URL
	Author      string `json:"author"`      // 上传人
	Name        string `json:"name"`        // 附件名
	Description string `json:"description"` // 附件描述
	Time        string `json:"time"`        // 上传时间
}

type TaskDetailRequest struct {
	Id string `uri:"id" label:"任务ID"` // 任务ID
}

type CompleteRequest struct {
	Id string `uri:"id" label:"任务ID"` // 任务ID
}

type CompleteWithFormRequest struct {
	Id         string       `uri:"id" label:"任务ID"` // 任务ID
	Properties []Properties `json:"properties"`
}

type Properties struct {
	Id    string      `json:"id"`
	Value interface{} `json:"value"`
}

type DelegateRequest struct {
	Id     string `uri:"id" label:"任务ID"`         // 任务ID
	ToUser int    `json:"toUser" label:"被指派人的ID"` // 被指派人的ID
}

type AddAttachmentRequest struct {
	Id          string `uri:"id" label:"任务ID"`                              // 任务ID
	Name        string `form:"name" binding:"required" label:"文件名(必填)"`     // 文件名(必填)
	Description string `form:"description" label:"描述"`                      // 描述
	ExternalUrl string `form:"externalUrl" label:"文件外链 (文件外链和文件(file)二选一)"` // 文件外链 (文件外链和文件(file)二选一)
}

type DelAttachmentRequest struct {
	TaskId string `uri:"taskId" label:"任务ID"` // 任务ID
	FileId string `uri:"fileId" label:"文件ID"` // 文件ID
}

type AddCommentRequest struct {
	TaskId  string `uri:"taskId" label:"任务ID"` // 任务ID
	Message string `json:"message" label:"备注"` // 备注
}

type DelCommentRequest struct {
	TaskId    string `uri:"taskId" label:"任务ID"`    // 任务ID
	CommentId string `uri:"commentId" label:"备注ID"` // 备注ID
}

type DownloadAttachmentRequest struct {
	TaskId       string `uri:"taskId" label:"任务ID"`       // 任务ID
	AttachmentId string `uri:"attachmentId" label:"附件ID"` // 附件ID
	FileName     string `uri:"fileName" label:"附件名"`      // 附件名
}
