// Code generated by goctl. DO NOT EDIT.
package process

type ListProcessRequest struct {
	Page     int    `form:"page" label:"分页"`       // 分页
	PageSize int    `form:"pageSize" label:"每页条数"` // 每页条数
	Name     string `form:"name" label:"流程名称"`     // 流程名称
}

type ListProcessResponse struct {
	Page     int           `json:"page"`     // 分页
	PageSize int           `json:"pageSize"` // 每页条数
	Total    int           `json:"total"`    // 总条数
	Data     []ListProcess `json:"data"`     // 具体数据
}

type ListProcess struct {
	Id           string `json:"id"`           // 流程定义ID
	Name         string `json:"name"`         // 流程分类
	DeploymentId string `json:"deploymentId"` // 流程部署ID
	Key          string `json:"key"`          // 流程KEY
	Category     string `json:"category"`     //流程分类
	Suspended    bool   `json:"suspended"`    // 流程状态
	Version      string `json:"version"`      // 流程版本
}

type DetailProcessRequest struct {
	Id string `uri:"id" label:"流程ID"` // 流程ID
}

type DetailProcessResponse struct {
	Id   string `json:"id"`   // 流程id
	Name string `json:"name"` // 流程name
	Xml  string `json:"xml"`  // 流程XML
}

type AddProcessRequest struct {
	FileName string `json:"fileName" binding:"required" label:"文件名"` // 文件名
	Xml      string `json:"xml" binding:"required" label:"流程定义"`     // 流程定义
}

type AddProcessResponse struct {
	Id string `json:"id"` // 业务流程ID
}

type DeleteProcessRequest struct {
	Id string `uri:"id" label:"业务流程ID"` // 业务流程ID
}

type StartProcessRequest struct {
	Id string `uri:"id" label:"流程ID"` // 流程ID
}
