// Code generated by goctl. DO NOT EDIT.
package form

type FlowFormListRequest struct {
	Page     int    `form:"page,optional" label:"分页"`       // 分页
	PageSize int    `form:"pageSize,optional" label:"每页条数"` // 每页条数
	Name     string `form:"name,optional" label:"表单名"`      // 表单名
}

type FlowFormListResponse struct {
	Page     int            `json:"page"`     // 分页
	PageSize int            `json:"pageSize"` // 每页条数
	Total    int            `json:"total"`    // 总条数
	Data     []FlowFormList `json:"data"`     // 具体数据
}

type FlowFormList struct {
	Id          string `json:"id"`
	Key         string `json:"key"`
	Version     int    `json:"version"`
	Name        string `json:"name"`        // 表单用途
	Description string `json:"description"` // 表单描述
}

type FlowFormDetailRequest struct {
	Id string `uri:"id"`
}

type FlowFormDetailResponse struct {
	Rule   string `json:"rule"`   // 表单回显使用
	Option string `json:"option"` // 表单回显使用
}

type FlowFormAddRequest struct {
	Key    string `json:"key" binding:"required"`
	Name   string `json:"name" binding:"required" label:"表单用途"`     // 表单用途
	Desc   string `json:"desc" binding:"required" label:"表单描述"`     // 表单描述
	Rule   string `json:"rule" binding:"required" label:"表单回显使用"`   // 表单回显使用
	Option string `json:"option" binding:"required" label:"表单回显使用"` // 表单回显使用
}

type FlowFormDeleteRequest struct {
	Id string `uri:"id"`
}
