// Code generated by goctl. DO NOT EDIT.
package process

import (
	"go-flow-admin/handler/flow/process"
	"go-flow-admin/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterFlowProcessRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/flow/process", process.ListHandle)
	g.GET("/flow/process/:id", process.DetailHandle)
	g.POST("/flow/process", process.AddHandle)
	g.DELETE("/flow/process/:id", process.DelHandle)
	g.POST("/flow/process/start/:id", process.StartHandle)

}
